# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a6455193bda7b98807e1c93bc15f3c98a475f5f14d864ee778ceeffc66f63f721df51c2e9c9bea6de9cadb80b262415341fc3d5de65d71b7f1194d8e50b4030

test:
  secret_key_base: b18583e8e51a58c4d8160b00f4d5ce7aeb7cfcfc187a117c56992d619fddc5c1f5625f064d1d8d7a99dbe426000954adb0d6d6cbbed2308eaf4bc3a473f67bef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
